import type { Rarity } from '@/content/schema/common';

/**
 * The full *Emberdawn* numbering plan (docs/03 Appendix A): all 130 cards with stable numbers, so
 * later phases fill in the rest without renumbering. `phase` says when a card is authored.
 * Order: element sections (Bloom, Ember, Tide, Volt, Terra, Mystic, Shade, Frost, Neutral), each
 * grouped by evolution line with a Nova right after its base card and the Legend closing the
 * section; then tactics (Items, Allies, Arenas); then the secret rares (IR story in time order,
 * SR, MR).
 */
export interface PlannedCard {
  number: number;
  name: string;
  kind: 'creature' | 'tactic' | 'essence';
  rarity: Rarity;
  tacticType?: 'item' | 'ally' | 'arena';
  /** Species slug (`gk.species.<slug>`). */
  species?: string;
  note?: string;
  phase: 2 | 3;
}

export const emberdawnPlan: readonly PlannedCard[] = [
  { number: 1, name: 'Budbun', kind: 'creature', rarity: 'common', species: 'budbun', phase: 2 },
  {
    number: 2,
    name: 'Bloomhop',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'bloomhop',
    phase: 2,
  },
  {
    number: 3,
    name: 'Sylvhare',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'sylvhare',
    phase: 3,
  },
  { number: 4, name: 'Puffcap', kind: 'creature', rarity: 'common', species: 'puffcap', phase: 3 },
  { number: 5, name: 'Fungloo', kind: 'creature', rarity: 'common', species: 'fungloo', phase: 3 },
  {
    number: 6,
    name: 'Mycelord',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'mycelord',
    phase: 3,
  },
  {
    number: 7,
    name: 'Mossquatch',
    kind: 'creature',
    rarity: 'rare',
    species: 'mossquatch',
    phase: 3,
  },
  {
    number: 8,
    name: 'Flickerfly',
    kind: 'creature',
    rarity: 'common',
    species: 'flickerfly',
    phase: 3,
  },
  {
    number: 9,
    name: 'Magmadillo',
    kind: 'creature',
    rarity: 'common',
    species: 'magmadillo',
    phase: 2,
  },
  {
    number: 10,
    name: 'Magmadillo',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'magmadillo',
    phase: 2,
  },
  {
    number: 11,
    name: 'Magmadillo Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    species: 'magmadillo',
    phase: 3,
  },
  {
    number: 12,
    name: 'Emberpup',
    kind: 'creature',
    rarity: 'common',
    species: 'emberpup',
    phase: 2,
  },
  {
    number: 13,
    name: 'Emberpup',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'emberpup',
    phase: 2,
  },
  {
    number: 14,
    name: 'Blazehound',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'blazehound',
    phase: 2,
  },
  { number: 15, name: 'Infernox', kind: 'creature', rarity: 'rare', species: 'infernox', phase: 2 },
  {
    number: 16,
    name: 'Infernox Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    species: 'infernox',
    phase: 2,
  },
  {
    number: 17,
    name: 'Solaryx',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'solaryx',
    note: 'Legend',
    phase: 2,
  },
  {
    number: 18,
    name: 'Solaryx Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    species: 'solaryx',
    phase: 2,
  },
  {
    number: 19,
    name: 'Trilobyte',
    kind: 'creature',
    rarity: 'common',
    species: 'trilobyte',
    phase: 3,
  },
  { number: 20, name: 'Shellby', kind: 'creature', rarity: 'common', species: 'shellby', phase: 3 },
  {
    number: 21,
    name: 'Bastionaut',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'bastionaut',
    phase: 3,
  },
  { number: 22, name: 'Tidepup', kind: 'creature', rarity: 'common', species: 'tidepup', phase: 3 },
  {
    number: 23,
    name: 'Walrusk',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'walrusk',
    phase: 3,
  },
  { number: 24, name: 'Sploot', kind: 'creature', rarity: 'uncommon', species: 'sploot', phase: 2 },
  {
    number: 25,
    name: 'Axolagoon',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'axolagoon',
    phase: 3,
  },
  { number: 26, name: 'Tsunamaw', kind: 'creature', rarity: 'rare', species: 'tsunamaw', phase: 3 },
  {
    number: 27,
    name: 'Maelstryx',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'maelstryx',
    note: 'Legend cameo',
    phase: 3,
  },
  { number: 28, name: 'Zapcoon', kind: 'creature', rarity: 'common', species: 'zapcoon', phase: 2 },
  {
    number: 29,
    name: 'Voltbandit',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'voltbandit',
    phase: 2,
  },
  {
    number: 30,
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'common',
    species: 'boltbuck',
    phase: 2,
  },
  {
    number: 31,
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'boltbuck',
    phase: 2,
  },
  {
    number: 32,
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'boltbuck',
    phase: 2,
  },
  {
    number: 33,
    name: 'Boltbuck Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    species: 'boltbuck',
    phase: 3,
  },
  { number: 34, name: 'Sparkit', kind: 'creature', rarity: 'common', species: 'sparkit', phase: 2 },
  {
    number: 35,
    name: 'Sparkit',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'sparkit',
    phase: 2,
  },
  {
    number: 36,
    name: 'Voltail',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'voltail',
    phase: 2,
  },
  {
    number: 37,
    name: 'Thundervixen',
    kind: 'creature',
    rarity: 'rare',
    species: 'thundervixen',
    phase: 2,
  },
  {
    number: 38,
    name: 'Thundervixen Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    species: 'thundervixen',
    phase: 2,
  },
  { number: 39, name: 'Pebblit', kind: 'creature', rarity: 'common', species: 'pebblit', phase: 2 },
  { number: 40, name: 'Pebblit', kind: 'creature', rarity: 'common', species: 'pebblit', phase: 3 },
  {
    number: 41,
    name: 'Bouldrake',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'bouldrake',
    phase: 3,
  },
  {
    number: 42,
    name: 'Molemite',
    kind: 'creature',
    rarity: 'common',
    species: 'molemite',
    phase: 3,
  },
  {
    number: 43,
    name: 'Tunnelord',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'tunnelord',
    phase: 3,
  },
  {
    number: 44,
    name: 'Amberwing',
    kind: 'creature',
    rarity: 'common',
    species: 'amberwing',
    note: 'Fossil',
    phase: 3,
  },
  {
    number: 45,
    name: 'Rexolith',
    kind: 'creature',
    rarity: 'rare',
    species: 'rexolith',
    note: 'Fossil, evolves from Amber Fossil',
    phase: 3,
  },
  {
    number: 46,
    name: 'Mothlume',
    kind: 'creature',
    rarity: 'common',
    species: 'mothlume',
    phase: 3,
  },
  {
    number: 47,
    name: 'Aurorwing',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'aurorwing',
    phase: 3,
  },
  {
    number: 48,
    name: 'Runeling',
    kind: 'creature',
    rarity: 'common',
    species: 'runeling',
    phase: 3,
  },
  {
    number: 49,
    name: 'Oracleon',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'oracleon',
    phase: 3,
  },
  {
    number: 50,
    name: 'Glowtoad',
    kind: 'creature',
    rarity: 'common',
    species: 'glowtoad',
    phase: 3,
  },
  {
    number: 51,
    name: 'Glowtoad',
    kind: 'creature',
    rarity: 'common',
    species: 'glowtoad',
    phase: 3,
  },
  { number: 52, name: 'Wisplet', kind: 'creature', rarity: 'common', species: 'wisplet', phase: 3 },
  { number: 53, name: 'Wisplet', kind: 'creature', rarity: 'common', species: 'wisplet', phase: 3 },
  {
    number: 54,
    name: 'Phantomane',
    kind: 'creature',
    rarity: 'holoRare',
    species: 'phantomane',
    phase: 3,
  },
  { number: 55, name: 'Dusklet', kind: 'creature', rarity: 'common', species: 'dusklet', phase: 3 },
  {
    number: 56,
    name: 'Nocturnowl',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'nocturnowl',
    phase: 3,
  },
  { number: 57, name: 'Umbraith', kind: 'creature', rarity: 'rare', species: 'umbraith', phase: 3 },
  {
    number: 58,
    name: 'Frostling',
    kind: 'creature',
    rarity: 'common',
    species: 'frostling',
    note: 'Snowcap of the caldera',
    phase: 3,
  },
  {
    number: 59,
    name: 'Glacierra',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'glacierra',
    phase: 3,
  },
  {
    number: 60,
    name: 'Pengwing',
    kind: 'creature',
    rarity: 'common',
    species: 'pengwing',
    phase: 3,
  },
  {
    number: 61,
    name: 'Crystalynx',
    kind: 'creature',
    rarity: 'rare',
    species: 'crystalynx',
    phase: 3,
  },
  { number: 62, name: 'Chirpip', kind: 'creature', rarity: 'common', species: 'chirpip', phase: 2 },
  {
    number: 63,
    name: 'Chirpip',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'chirpip',
    phase: 3,
  },
  {
    number: 64,
    name: 'Galewing',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'galewing',
    phase: 2,
  },
  {
    number: 65,
    name: 'Stormcrest',
    kind: 'creature',
    rarity: 'rare',
    species: 'stormcrest',
    phase: 2,
  },
  { number: 66, name: 'Nibblit', kind: 'creature', rarity: 'common', species: 'nibblit', phase: 3 },
  { number: 67, name: 'Nibblit', kind: 'creature', rarity: 'common', species: 'nibblit', phase: 3 },
  { number: 68, name: 'Mimicat', kind: 'creature', rarity: 'common', species: 'mimicat', phase: 2 },
  {
    number: 69,
    name: 'Mimicat',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'mimicat',
    phase: 3,
  },
  { number: 70, name: 'Snoozle', kind: 'creature', rarity: 'common', species: 'snoozle', phase: 2 },
  {
    number: 71,
    name: 'Snoozle',
    kind: 'creature',
    rarity: 'uncommon',
    species: 'snoozle',
    phase: 3,
  },
  {
    number: 72,
    name: 'Snoozle Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    species: 'snoozle',
    phase: 3,
  },
  {
    number: 73,
    name: 'Glimmer Potion',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    phase: 2,
  },
  {
    number: 74,
    name: 'Spark Charm',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    phase: 2,
  },
  {
    number: 75,
    name: 'Trail Snack',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    phase: 3,
  },
  {
    number: 76,
    name: 'Cinder Stone',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    phase: 3,
  },
  {
    number: 77,
    name: 'Amber Fossil',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    note: 'Rexolith evolves from it',
    phase: 3,
  },
  { number: 78, name: 'Dash Net', kind: 'tactic', rarity: 'common', tacticType: 'item', phase: 3 },
  {
    number: 79,
    name: 'Rescue Rope',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    phase: 3,
  },
  {
    number: 80,
    name: 'Ember Lantern',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'item',
    phase: 2,
  },
  {
    number: 81,
    name: 'Explorer’s Map',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'item',
    phase: 3,
  },
  {
    number: 82,
    name: 'Volcano Goggles',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'item',
    phase: 3,
  },
  {
    number: 83,
    name: 'Island Compass',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'item',
    phase: 3,
  },
  {
    number: 84,
    name: 'Shell Horn',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    phase: 3,
  },
  {
    number: 85,
    name: 'Ranger Tala',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'ally',
    phase: 2,
  },
  {
    number: 86,
    name: 'Volcanologist Vera',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'ally',
    phase: 3,
  },
  {
    number: 87,
    name: 'Captain Maru',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'ally',
    phase: 3,
  },
  {
    number: 88,
    name: 'Theo’s Advice',
    kind: 'tactic',
    rarity: 'rare',
    tacticType: 'ally',
    note: 'Theo Hartley',
    phase: 2,
  },
  {
    number: 89,
    name: 'Milo’s Cheer',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'ally',
    note: 'Milo Okafor',
    phase: 3,
  },
  {
    number: 90,
    name: 'Dex’s Deckcraft',
    kind: 'tactic',
    rarity: 'rare',
    tacticType: 'ally',
    note: 'Dex Park',
    phase: 3,
  },
  {
    number: 91,
    name: 'Grandma Rosa’s Tea',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'ally',
    note: 'Rosa Bellini',
    phase: 3,
  },
  {
    number: 92,
    name: 'Vivian’s Appraisal',
    kind: 'tactic',
    rarity: 'rare',
    tacticType: 'ally',
    note: 'Vivian Chen',
    phase: 3,
  },
  {
    number: 93,
    name: 'Professor Lumen',
    kind: 'tactic',
    rarity: 'rare',
    tacticType: 'ally',
    phase: 3,
  },
  {
    number: 94,
    name: 'Emberdawn Caldera',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'arena',
    phase: 2,
  },
  {
    number: 95,
    name: 'Sunrise Summit',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'arena',
    phase: 3,
  },
  {
    number: 96,
    name: 'Glowmoss Lagoon',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'arena',
    phase: 3,
  },
  {
    number: 97,
    name: 'Thunderhead Plateau',
    kind: 'tactic',
    rarity: 'rare',
    tacticType: 'arena',
    phase: 2,
  },
  {
    number: 98,
    name: 'Brightbay Harbor',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'arena',
    phase: 3,
  },
  {
    number: 99,
    name: 'Crystal Cavern',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'arena',
    phase: 3,
  },
  {
    number: 100,
    name: 'Solaryx’s Aerie',
    kind: 'tactic',
    rarity: 'rare',
    tacticType: 'arena',
    phase: 3,
  },
  {
    number: 101,
    name: 'Budbun',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'budbun',
    note: '1. First Light (dawn)',
    phase: 3,
  },
  {
    number: 102,
    name: 'Magmadillo',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'magmadillo',
    note: '2. Warm Rocks (sunrise)',
    phase: 2,
  },
  {
    number: 103,
    name: 'Chirpip',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'chirpip',
    note: '3. Morning Chorus',
    phase: 3,
  },
  {
    number: 104,
    name: 'Pebblit',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'pebblit',
    note: '4. Rolling Start (morning)',
    phase: 3,
  },
  {
    number: 105,
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'boltbuck',
    note: '5. Noon Thunder',
    phase: 2,
  },
  {
    number: 106,
    name: 'Zapcoon',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'zapcoon',
    note: '6. Picnic Heist (afternoon)',
    phase: 3,
  },
  {
    number: 107,
    name: 'Voltail',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'voltail',
    note: '7. Afternoon Gust',
    phase: 3,
  },
  {
    number: 108,
    name: 'Sploot',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'sploot',
    note: '8. Dusk Hum (dusk)',
    phase: 2,
  },
  {
    number: 109,
    name: 'Tidepup',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'tidepup',
    note: '9. Sunset Swim',
    phase: 3,
  },
  {
    number: 110,
    name: 'Mothlume',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'mothlume',
    note: '10. Evening Glow',
    phase: 3,
  },
  {
    number: 111,
    name: 'Glowtoad',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'glowtoad',
    note: '11. Twilight Choir',
    phase: 3,
  },
  {
    number: 112,
    name: 'Wisplet',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'wisplet',
    note: '12. Lantern Wisps',
    phase: 3,
  },
  {
    number: 113,
    name: 'Dusklet',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'dusklet',
    note: '13. Moonrise',
    phase: 3,
  },
  {
    number: 114,
    name: 'Sparkit',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'sparkit',
    note: '14. Starlight Tail (night)',
    phase: 2,
  },
  {
    number: 115,
    name: 'Snoozle',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'snoozle',
    note: '15. Midnight Nap',
    phase: 3,
  },
  {
    number: 116,
    name: 'Blazehound',
    kind: 'creature',
    rarity: 'illustrationRare',
    species: 'blazehound',
    note: '16. Caldera Watch (deep night)',
    phase: 3,
  },
  {
    number: 117,
    name: 'Infernox',
    kind: 'creature',
    rarity: 'secretRare',
    species: 'infernox',
    note: 'Gold',
    phase: 2,
  },
  {
    number: 118,
    name: 'Thundervixen',
    kind: 'creature',
    rarity: 'secretRare',
    species: 'thundervixen',
    note: 'Gold',
    phase: 3,
  },
  {
    number: 119,
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'secretRare',
    species: 'boltbuck',
    note: 'Gold',
    phase: 3,
  },
  {
    number: 120,
    name: 'Magmadillo',
    kind: 'creature',
    rarity: 'secretRare',
    species: 'magmadillo',
    note: 'Gold',
    phase: 3,
  },
  {
    number: 121,
    name: 'Emberpup',
    kind: 'creature',
    rarity: 'secretRare',
    species: 'emberpup',
    note: 'Gold',
    phase: 2,
  },
  {
    number: 122,
    name: 'Sparkit',
    kind: 'creature',
    rarity: 'secretRare',
    species: 'sparkit',
    note: 'Gold',
    phase: 3,
  },
  {
    number: 123,
    name: 'Ranger Tala',
    kind: 'tactic',
    rarity: 'secretRare',
    tacticType: 'ally',
    note: 'Full-art Ally',
    phase: 3,
  },
  {
    number: 124,
    name: 'Theo’s Advice',
    kind: 'tactic',
    rarity: 'secretRare',
    tacticType: 'ally',
    note: 'Full-art Ally',
    phase: 3,
  },
  {
    number: 125,
    name: 'Ember Essence',
    kind: 'essence',
    rarity: 'secretRare',
    note: 'Textured Essence',
    phase: 3,
  },
  {
    number: 126,
    name: 'Volt Essence',
    kind: 'essence',
    rarity: 'secretRare',
    note: 'Textured Essence',
    phase: 3,
  },
  {
    number: 127,
    name: 'Sparkit',
    kind: 'creature',
    rarity: 'mythicRare',
    species: 'sparkit',
    note: '“Dawn Chase” (illustration)',
    phase: 3,
  },
  {
    number: 128,
    name: 'Infernox Nova',
    kind: 'creature',
    rarity: 'mythicRare',
    species: 'infernox',
    note: '“Nova Gold”',
    phase: 3,
  },
  {
    number: 129,
    name: 'Solaryx & Emberpup',
    kind: 'creature',
    rarity: 'mythicRare',
    species: 'solaryx',
    note: '“Bond” (both creatures)',
    phase: 3,
  },
  {
    number: 130,
    name: 'Solaryx',
    kind: 'creature',
    rarity: 'mythicRare',
    species: 'solaryx',
    note: '“Gold Crown”',
    phase: 2,
  },
];
