import type { CardDef, PackConfigDef, ProductDef, SetDef } from '@/content/schema/tcg';
import { dollars } from '@/core/money';

/**
 * Emberdawn (EMD): the current set at game start (docs/03 §4.1).
 * Phase 1 ships a small spike subset used by the Art Spike cards and the engine sandbox.
 * The full 130-card list arrives in Phase 2 (subset) and Phase 3 (full).
 */
export const emberdawn: SetDef = {
  id: 'gk.emberdawn',
  brandId: 'gk',
  code: 'EMD',
  name: 'Emberdawn',
  era: 'modern',
  releaseDay: -6,
  totalMain: 100,
  theme: 'A volcanic island at sunrise, where the sun phoenix Solaryx returns.',
};

export const emberdawnCards: readonly CardDef[] = [
  {
    id: 'gk.emberdawn.012',
    setId: 'gk.emberdawn',
    number: 12,
    name: 'Emberpup',
    kind: 'creature',
    rarity: 'common',
    finishes: ['normal', 'reverseHolo'],
    speciesId: 'gk.species.emberpup',
    element: 'ember',
    stage: 'basic',
    hp: 60,
    attacks: [
      {
        name: 'Tail Toast',
        cost: ['ember'],
        damage: '10',
        text: 'Heal 10 damage from this creature.',
      },
      { name: 'Ember Pounce', cost: ['ember', 'neutral'], damage: '30' },
    ],
    weakness: 'tide',
    retreat: 1,
    flavor: 'The flame on its tail wags faster when it is happy, which is almost always.',
    illustrator: 'Mika Arai',
    art: {
      composition: 'window',
      speciesId: 'gk.species.emberpup',
      pose: 'idle',
      timeOfDay: 'day',
      seed: 1204,
    },
    baseValueCents: dollars(0.15),
    playability: 0.1,
  },
  {
    id: 'gk.emberdawn.024',
    setId: 'gk.emberdawn',
    number: 24,
    name: 'Sploot',
    kind: 'creature',
    rarity: 'uncommon',
    finishes: ['normal', 'reverseHolo'],
    speciesId: 'gk.species.sploot',
    element: 'tide',
    stage: 'basic',
    hp: 70,
    attacks: [
      {
        name: 'Splash Nap',
        cost: ['tide'],
        damage: '',
        text: 'Heal 30 damage. This creature is now Asleep.',
      },
      { name: 'Bubble Belly', cost: ['tide', 'neutral'], damage: '30' },
    ],
    weakness: 'volt',
    retreat: 2,
    flavor: 'Sploot flops onto warm rocks to nap. Its frilly gills change color with its mood.',
    illustrator: 'Tomás Reyes',
    art: {
      composition: 'window',
      speciesId: 'gk.species.sploot',
      pose: 'idle',
      timeOfDay: 'day',
      seed: 2407,
    },
    baseValueCents: dollars(0.25),
    playability: 0.15,
  },
  {
    id: 'gk.emberdawn.035',
    setId: 'gk.emberdawn',
    number: 35,
    name: 'Sparkit',
    kind: 'creature',
    rarity: 'holoRare',
    finishes: ['holo'],
    speciesId: 'gk.species.sparkit',
    element: 'volt',
    stage: 'basic',
    hp: 70,
    ability: {
      name: 'Static Charge',
      text: 'Once during your turn, you may attach a Volt Essence from your hand to this creature.',
    },
    attacks: [{ name: 'Spark Dash', cost: ['volt', 'neutral'], damage: '40' }],
    weakness: 'terra',
    retreat: 1,
    flavor:
      'Its tail tip stores static from every step it takes. On stormy nights it glows like a tiny star.',
    illustrator: 'Juniper Holt',
    art: {
      composition: 'window',
      speciesId: 'gk.species.sparkit',
      pose: 'idle',
      timeOfDay: 'dusk',
      seed: 3501,
    },
    baseValueCents: dollars(3.5),
    playability: 0.35,
  },
  {
    id: 'gk.emberdawn.108',
    setId: 'gk.emberdawn',
    number: 108,
    name: 'Sploot',
    kind: 'creature',
    rarity: 'illustrationRare',
    finishes: ['fullArtTextured'],
    speciesId: 'gk.species.sploot',
    element: 'tide',
    stage: 'basic',
    hp: 70,
    attacks: [
      {
        name: 'Lagoon Lullaby',
        cost: ['tide', 'neutral'],
        damage: '50',
        text: 'Both creatures fall Asleep.',
      },
    ],
    weakness: 'volt',
    retreat: 2,
    flavor: 'At dusk, whole families of Sploot drift together, humming to the tide.',
    illustrator: 'Sora Lind',
    art: {
      composition: 'fullArt',
      speciesId: 'gk.species.sploot',
      pose: 'happy',
      timeOfDay: 'dusk',
      seed: 10801,
    },
    baseValueCents: dollars(16),
    playability: 0.15,
  },
  {
    id: 'gk.emberdawn.121',
    setId: 'gk.emberdawn',
    number: 121,
    name: 'Emberpup',
    kind: 'creature',
    rarity: 'secretRare',
    finishes: ['gold'],
    speciesId: 'gk.species.emberpup',
    element: 'ember',
    stage: 'basic',
    hp: 60,
    attacks: [{ name: 'Golden Blaze', cost: ['ember', 'ember'], damage: '70' }],
    weakness: 'tide',
    retreat: 1,
    flavor: 'Legends say a golden Emberpup lights the first sunrise of every season.',
    illustrator: 'Kaito Brenner',
    art: {
      composition: 'fullArt',
      speciesId: 'gk.species.emberpup',
      pose: 'action',
      timeOfDay: 'day',
      seed: 12101,
    },
    baseValueCents: dollars(38),
    playability: 0.1,
  },
];

/** Standard modern Glimmerkin booster (docs/02 §11.1). */
export const gkModernBooster: PackConfigDef = {
  id: 'gk.pack.modern',
  cardsPerPack: 10,
  slots: [
    { count: 5, table: [{ rarity: 'common', weight: 1 }] },
    { count: 3, table: [{ rarity: 'uncommon', weight: 1 }] },
    {
      count: 1,
      table: [
        { rarity: 'common', finish: 'reverseHolo', weight: 60 },
        { rarity: 'uncommon', finish: 'reverseHolo', weight: 30 },
        { rarity: 'rare', finish: 'reverseHolo', weight: 10 },
      ],
    },
    {
      count: 1,
      table: [
        { rarity: 'rare', weight: 62.5 },
        { rarity: 'holoRare', weight: 25 },
        { rarity: 'ultraRare', weight: 8 },
        { rarity: 'illustrationRare', weight: 3 },
        { rarity: 'secretRare', weight: 1.2 },
        { rarity: 'mythicRare', weight: 0.3 },
      ],
    },
  ],
  godPack: {
    chance: 1 / 2000,
    table: [
      { rarity: 'illustrationRare', weight: 75 },
      { rarity: 'secretRare', weight: 20 },
      { rarity: 'mythicRare', weight: 5 },
    ],
  },
  misprintChancePerCard: 1 / 5000,
};

/** Emberdawn sealed products (docs/02 §10.1). */
export const emberdawnProducts: readonly ProductDef[] = [
  {
    id: 'gk.emberdawn.booster',
    kind: 'booster',
    name: 'Emberdawn Booster Pack',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(4.49),
    storageUnits: 1,
    perShelfSlot: 12,
    packConfigId: 'gk.pack.modern',
    contents: [],
  },
  {
    id: 'gk.emberdawn.blister',
    kind: 'blister',
    name: 'Emberdawn 3-Pack Blister',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(14.99),
    storageUnits: 2,
    perShelfSlot: 4,
    contents: [{ type: 'pack', productId: 'gk.emberdawn.booster', count: 3 }],
  },
  {
    id: 'gk.emberdawn.starter-ember',
    kind: 'starterDeck',
    name: 'Emberdawn Starter Deck: Ember Blaze',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(14.99),
    storageUnits: 2,
    perShelfSlot: 4,
    contents: [],
  },
  {
    id: 'gk.emberdawn.box',
    kind: 'box',
    name: 'Emberdawn Booster Box (36 packs)',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(161.64),
    storageUnits: 18,
    perShelfSlot: 1,
    contents: [{ type: 'pack', productId: 'gk.emberdawn.booster', count: 36 }],
  },
];
