import type { CardDef, PackConfigDef, ProductDef, SetDef } from '@/content/schema/tcg';
import { dollars } from '@/core/money';

/**
 * Emberdawn (EMD): the current set at game start (docs/03 §4.1). The full 130-card numbering plan
 * is docs/03 Appendix A; Phase 2 authors the 42-card subset below, Phase 3 fills in the rest.
 */
export const emberdawn: SetDef = {
  id: 'gk.emberdawn',
  brandId: 'gk',
  code: 'EMD',
  name: 'Emberdawn',
  era: 'modern',
  releaseDay: -6,
  totalMain: 100,
  theme: 'A volcanic island at sunrise, where the sun phoenix Solaryx returns.',
};

type CardInput = Omit<CardDef, 'id' | 'setId' | 'number' | 'finishes' | 'art'> & {
  finishes?: CardDef['finishes'];
  art: Omit<CardDef['art'], 'pose' | 'timeOfDay'> &
    Partial<Pick<CardDef['art'], 'pose' | 'timeOfDay'>>;
};

/** Printed finishes by rarity (docs/03 §3.4). */
const FINISHES: Record<CardDef['rarity'], CardDef['finishes']> = {
  common: ['normal', 'reverseHolo'],
  uncommon: ['normal', 'reverseHolo'],
  rare: ['normal', 'reverseHolo'],
  holoRare: ['holo'],
  ultraRare: ['fullArtTextured'],
  illustrationRare: ['fullArtTextured'],
  secretRare: ['gold'],
  mythicRare: ['cosmos'],
  promo: ['cosmos'],
};

/** An Emberdawn card: id, set and finishes follow from the number and rarity. */
function emd(number: number, input: CardInput): CardDef {
  return {
    ...input,
    id: `gk.emberdawn.${String(number).padStart(3, '0')}`,
    setId: 'gk.emberdawn',
    number,
    finishes: input.finishes ?? FINISHES[input.rarity],
    art: { pose: 'idle', timeOfDay: 'day', ...input.art },
  };
}

const sp = (slug: string) => `gk.species.${slug}`;

/**
 * The Phase 2 subset: 42 of the 130 planned cards (docs/03 Appendix A keeps every number stable).
 * Values follow docs/02 §7.1 (typical × relative popularity × playability bump × art appeal),
 * normalized within each rarity so pack EV stays on target (§11.3, see Appendix A notes).
 */
export const emberdawnCards: readonly CardDef[] = [
  // ---- Bloom ----
  emd(1, {
    name: 'Budbun',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('budbun'),
    element: 'bloom',
    stage: 'basic',
    hp: 50,
    attacks: [
      { name: 'Nibble', cost: ['bloom'], damage: '10' },
      {
        name: 'Ear Flap',
        cost: ['bloom', 'neutral'],
        damage: '20',
        text: 'Heal 10 damage from this creature.',
      },
    ],
    weakness: 'ember',
    retreat: 1,
    flavor: 'Its leaf ears turn toward the sun. On cloudy days it just sits and waits.',
    illustrator: 'Ines Calloway',
    art: { composition: 'window', speciesId: sp('budbun'), pose: 'happy', seed: 101 },
    baseValueCents: dollars(0.12),
    playability: 0.1,
  }),
  emd(2, {
    name: 'Bloomhop',
    kind: 'creature',
    rarity: 'uncommon',
    speciesId: sp('bloomhop'),
    element: 'bloom',
    stage: 'stage1',
    hp: 90,
    attacks: [
      {
        name: 'Petal Hop',
        cost: ['bloom'],
        damage: '20',
        text: 'Your opponent can’t retreat during their next turn.',
      },
      { name: 'Blossom Kick', cost: ['bloom', 'bloom', 'neutral'], damage: '60' },
    ],
    weakness: 'ember',
    retreat: 1,
    flavor: 'Every spring its crown blooms a new color. No two meadows agree on which is best.',
    illustrator: 'Ines Calloway',
    art: { composition: 'window', speciesId: sp('bloomhop'), seed: 201 },
    baseValueCents: dollars(0.16),
    playability: 0.15,
  }),
  // ---- Ember ----
  emd(9, {
    name: 'Magmadillo',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('magmadillo'),
    element: 'ember',
    stage: 'basic',
    hp: 80,
    attacks: [
      {
        name: 'Roll Up',
        cost: ['ember'],
        text: 'During your opponent’s next turn, prevent 20 damage done to this creature.',
      },
      { name: 'Hot Shell', cost: ['ember', 'neutral', 'neutral'], damage: '50' },
    ],
    weakness: 'tide',
    retreat: 2,
    flavor: 'It curls up on cooling lava flows and naps until the rock is cold enough to eat.',
    illustrator: 'Bo Strand',
    art: { composition: 'window', speciesId: sp('magmadillo'), seed: 901 },
    baseValueCents: dollars(0.07),
    playability: 0.15,
  }),
  emd(10, {
    name: 'Magmadillo',
    kind: 'creature',
    rarity: 'holoRare',
    speciesId: sp('magmadillo'),
    element: 'ember',
    stage: 'basic',
    hp: 90,
    ability: { name: 'Basalt Plates', text: 'This creature takes 20 less damage from attacks.' },
    attacks: [{ name: 'Lava Roll', cost: ['ember', 'ember', 'neutral'], damage: '70' }],
    weakness: 'tide',
    retreat: 2,
    flavor: 'The seams between its plates glow brighter the angrier the volcano gets.',
    illustrator: 'Bo Strand',
    art: {
      composition: 'window',
      speciesId: sp('magmadillo'),
      pose: 'happy',
      timeOfDay: 'dusk',
      seed: 1001,
    },
    baseValueCents: dollars(1.34),
    playability: 0.3,
  }),
  emd(12, {
    name: 'Emberpup',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('emberpup'),
    element: 'ember',
    stage: 'basic',
    hp: 60,
    attacks: [
      {
        name: 'Tail Toast',
        cost: ['ember'],
        damage: '10',
        text: 'Heal 10 damage from this creature.',
      },
      { name: 'Ember Pounce', cost: ['ember', 'neutral'], damage: '30' },
    ],
    weakness: 'tide',
    retreat: 1,
    flavor: 'The flame on its tail wags faster when it is happy, which is almost always.',
    illustrator: 'Mika Arai',
    art: { composition: 'window', speciesId: sp('emberpup'), seed: 1204 },
    baseValueCents: dollars(0.12),
    playability: 0.1,
  }),
  emd(13, {
    name: 'Emberpup',
    kind: 'creature',
    rarity: 'holoRare',
    speciesId: sp('emberpup'),
    element: 'ember',
    stage: 'basic',
    hp: 70,
    ability: {
      name: 'Warm Welcome',
      text: 'Once during your turn, you may heal 20 damage from one of your Benched creatures.',
    },
    attacks: [{ name: 'Flare Fetch', cost: ['ember', 'neutral'], damage: '40' }],
    weakness: 'tide',
    retreat: 1,
    flavor: 'It brings back every stick you throw. Most of them are on fire by then.',
    illustrator: 'Mika Arai',
    art: {
      composition: 'window',
      speciesId: sp('emberpup'),
      pose: 'happy',
      timeOfDay: 'dusk',
      seed: 1301,
    },
    baseValueCents: dollars(2.26),
    playability: 0.3,
  }),
  emd(14, {
    name: 'Blazehound',
    kind: 'creature',
    rarity: 'uncommon',
    speciesId: sp('blazehound'),
    element: 'ember',
    stage: 'stage1',
    hp: 100,
    attacks: [
      {
        name: 'Smoke Signal',
        cost: ['ember'],
        text: 'Search your deck for an Ember Essence and attach it to this creature.',
      },
      { name: 'Blaze Bite', cost: ['ember', 'ember', 'neutral'], damage: '70' },
    ],
    weakness: 'tide',
    retreat: 2,
    flavor: 'It patrols the caldera rim at night. Lost hikers follow its glow home.',
    illustrator: 'Kaito Brenner',
    art: { composition: 'window', speciesId: sp('blazehound'), seed: 1401 },
    baseValueCents: dollars(0.19),
    playability: 0.2,
  }),
  emd(15, {
    name: 'Infernox',
    kind: 'creature',
    rarity: 'rare',
    speciesId: sp('infernox'),
    element: 'ember',
    stage: 'stage2',
    hp: 160,
    attacks: [
      {
        name: 'Scorch Howl',
        cost: ['ember', 'neutral'],
        damage: '50',
        text: 'Your opponent’s Active creature is now Burned.',
      },
      {
        name: 'Dragonfire',
        cost: ['ember', 'ember', 'ember', 'neutral'],
        damage: '150',
        text: 'Discard 2 Ember Essence from this creature.',
      },
    ],
    weakness: 'tide',
    retreat: 3,
    flavor: 'Old islanders say the volcano only sleeps because Infernox lies awake.',
    illustrator: 'Kaito Brenner',
    art: { composition: 'window', speciesId: sp('infernox'), seed: 1501 },
    baseValueCents: dollars(0.72),
    playability: 0.35,
  }),
  emd(16, {
    name: 'Infernox Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    speciesId: sp('infernox'),
    element: 'ember',
    stage: 'nova',
    hp: 260,
    ability: {
      name: 'Caldera Heart',
      text: 'Once during your turn, you may attach an Ember Essence from your discard pile to this creature.',
    },
    attacks: [
      {
        name: 'Nova Inferno',
        cost: ['ember', 'ember', 'ember', 'neutral'],
        damage: '240',
        text: 'This creature can’t attack during your next turn.',
      },
    ],
    weakness: 'tide',
    retreat: 3,
    flavor: 'When it goes Nova, the sunrise has competition.',
    illustrator: 'Dov Ashby',
    art: {
      composition: 'window',
      speciesId: sp('infernox'),
      pose: 'action',
      timeOfDay: 'night',
      seed: 1601,
    },
    baseValueCents: dollars(8.98),
    playability: 0.7,
  }),
  emd(17, {
    name: 'Solaryx',
    kind: 'creature',
    rarity: 'holoRare',
    speciesId: sp('solaryx'),
    element: 'ember',
    stage: 'legend',
    hp: 170,
    ability: {
      name: 'First Light',
      text: 'When you play this creature, heal 30 damage from each of your creatures.',
    },
    attacks: [{ name: 'Sunwing Sweep', cost: ['ember', 'ember', 'neutral'], damage: '110' }],
    weakness: 'tide',
    retreat: 2,
    flavor: 'Each dawn it dips one wing into the caldera and carries the first light over the sea.',
    illustrator: 'Juniper Holt',
    art: { composition: 'window', speciesId: sp('solaryx'), pose: 'happy', seed: 1701 },
    baseValueCents: dollars(3.35),
    playability: 0.5,
  }),
  emd(18, {
    name: 'Solaryx Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    speciesId: sp('solaryx'),
    element: 'ember',
    stage: 'nova',
    hp: 280,
    ability: {
      name: 'Endless Dawn',
      text: 'Once during your turn, you may move an Ember Essence from one of your creatures to another.',
    },
    attacks: [
      {
        name: 'Solar Crown',
        cost: ['ember', 'ember', 'ember'],
        damage: '200',
        text: 'Heal 50 damage from this creature.',
      },
    ],
    weakness: 'tide',
    retreat: 2,
    flavor: 'Its wingbeat warms the whole island by a degree.',
    illustrator: 'Juniper Holt',
    art: {
      composition: 'window',
      speciesId: sp('solaryx'),
      pose: 'action',
      timeOfDay: 'dusk',
      seed: 1801,
    },
    baseValueCents: dollars(8.34),
    playability: 0.75,
  }),
  // ---- Tide ----
  emd(24, {
    name: 'Sploot',
    kind: 'creature',
    rarity: 'uncommon',
    speciesId: sp('sploot'),
    element: 'tide',
    stage: 'basic',
    hp: 70,
    attacks: [
      {
        name: 'Splash Nap',
        cost: ['tide'],
        damage: '',
        text: 'Heal 30 damage. This creature is now Asleep.',
      },
      { name: 'Bubble Belly', cost: ['tide', 'neutral'], damage: '30' },
    ],
    weakness: 'volt',
    retreat: 2,
    flavor: 'Sploot flops onto warm rocks to nap. Its frilly gills change color with its mood.',
    illustrator: 'Tomás Reyes',
    art: { composition: 'window', speciesId: sp('sploot'), seed: 2407 },
    baseValueCents: dollars(0.29),
    playability: 0.15,
  }),
  // ---- Volt ----
  emd(28, {
    name: 'Zapcoon',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('zapcoon'),
    element: 'volt',
    stage: 'basic',
    hp: 60,
    attacks: [
      { name: 'Snack Swipe', cost: ['neutral'], text: 'Look at your opponent’s hand.' },
      {
        name: 'Static Tail',
        cost: ['volt', 'neutral'],
        damage: '30',
        text: 'Flip a coin. If heads, your opponent’s Active creature is now Paralyzed.',
      },
    ],
    weakness: 'terra',
    retreat: 1,
    flavor: 'Picnic baskets on the island come with a warning sticker about Zapcoon.',
    illustrator: 'Arlo Penn',
    art: { composition: 'window', speciesId: sp('zapcoon'), pose: 'happy', seed: 2801 },
    baseValueCents: dollars(0.07),
    playability: 0.1,
  }),
  emd(29, {
    name: 'Voltbandit',
    kind: 'creature',
    rarity: 'holoRare',
    speciesId: sp('voltbandit'),
    element: 'volt',
    stage: 'stage1',
    hp: 110,
    ability: {
      name: 'Light Fingers',
      text: 'Once during your turn, you may look at the top card of your opponent’s deck. You may discard it.',
    },
    attacks: [
      {
        name: 'Charged Getaway',
        cost: ['volt', 'neutral'],
        damage: '60',
        text: 'Switch this creature with one of your Benched creatures.',
      },
    ],
    weakness: 'terra',
    retreat: 1,
    flavor: 'It never takes more than it can carry, which, with a tail like that, is a lot.',
    illustrator: 'Arlo Penn',
    art: {
      composition: 'window',
      speciesId: sp('voltbandit'),
      pose: 'action',
      timeOfDay: 'night',
      seed: 2901,
    },
    baseValueCents: dollars(1.62),
    playability: 0.45,
  }),
  emd(30, {
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('boltbuck'),
    element: 'volt',
    stage: 'basic',
    hp: 80,
    attacks: [
      { name: 'Antler Spark', cost: ['volt'], damage: '20' },
      {
        name: 'Thunder Charge',
        cost: ['volt', 'volt', 'neutral'],
        damage: '60',
        text: 'This creature also does 10 damage to itself.',
      },
    ],
    weakness: 'terra',
    retreat: 2,
    flavor: 'Herds gather on the plateau before a storm. Their antlers hum like power lines.',
    illustrator: 'Maren Solberg',
    art: { composition: 'window', speciesId: sp('boltbuck'), seed: 3001 },
    baseValueCents: dollars(0.09),
    playability: 0.15,
  }),
  emd(31, {
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'uncommon',
    speciesId: sp('boltbuck'),
    element: 'volt',
    stage: 'basic',
    hp: 90,
    attacks: [
      {
        name: 'Call the Storm',
        cost: ['volt'],
        text: 'Attach a Volt Essence from your discard pile to one of your creatures.',
      },
      { name: 'Static Stomp', cost: ['volt', 'volt'], damage: '50' },
    ],
    weakness: 'terra',
    retreat: 2,
    flavor: 'A young buck’s first antlers crackle so much it can’t sneak up on anyone.',
    illustrator: 'Maren Solberg',
    art: {
      composition: 'window',
      speciesId: sp('boltbuck'),
      pose: 'happy',
      timeOfDay: 'dusk',
      seed: 3101,
    },
    baseValueCents: dollars(0.18),
    playability: 0.25,
  }),
  emd(32, {
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'holoRare',
    speciesId: sp('boltbuck'),
    element: 'volt',
    stage: 'basic',
    hp: 90,
    ability: {
      name: 'Lightning Rod',
      text: 'Whenever you attach a Volt Essence to this creature, draw a card.',
    },
    attacks: [
      {
        name: 'Forked Bolt',
        cost: ['volt', 'volt', 'neutral'],
        damage: '80',
        text: 'Also do 20 damage to one of your opponent’s Benched creatures.',
      },
    ],
    weakness: 'terra',
    retreat: 2,
    flavor: 'Lightning on the plateau always strikes twice: once for each antler.',
    illustrator: 'Maren Solberg',
    art: {
      composition: 'window',
      speciesId: sp('boltbuck'),
      pose: 'action',
      timeOfDay: 'night',
      seed: 3201,
    },
    baseValueCents: dollars(1.54),
    playability: 0.4,
  }),
  emd(34, {
    name: 'Sparkit',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('sparkit'),
    element: 'volt',
    stage: 'basic',
    hp: 60,
    attacks: [
      { name: 'Zippy Dash', cost: ['neutral'], damage: '10' },
      { name: 'Tail Zap', cost: ['volt', 'neutral'], damage: '30' },
    ],
    weakness: 'terra',
    retreat: 1,
    flavor: 'Its tail tip stores static from every step it takes.',
    illustrator: 'Juniper Holt',
    art: { composition: 'window', speciesId: sp('sparkit'), pose: 'happy', seed: 3401 },
    baseValueCents: dollars(0.17),
    playability: 0.15,
  }),
  emd(35, {
    name: 'Sparkit',
    kind: 'creature',
    rarity: 'holoRare',
    speciesId: sp('sparkit'),
    element: 'volt',
    stage: 'basic',
    hp: 70,
    ability: {
      name: 'Static Charge',
      text: 'Once during your turn, you may attach a Volt Essence from your hand to this creature.',
    },
    attacks: [{ name: 'Spark Dash', cost: ['volt', 'neutral'], damage: '40' }],
    weakness: 'terra',
    retreat: 1,
    flavor:
      'Its tail tip stores static from every step it takes. On stormy nights it glows like a tiny star.',
    illustrator: 'Juniper Holt',
    art: { composition: 'window', speciesId: sp('sparkit'), timeOfDay: 'dusk', seed: 3501 },
    baseValueCents: dollars(3.09),
    playability: 0.35,
  }),
  emd(36, {
    name: 'Voltail',
    kind: 'creature',
    rarity: 'uncommon',
    speciesId: sp('voltail'),
    element: 'volt',
    stage: 'stage1',
    hp: 90,
    attacks: [
      {
        name: 'Quick Charge',
        cost: ['volt'],
        text: 'Search your deck for up to 2 Volt Essence and attach them to your creatures.',
      },
      {
        name: 'Thunder Pounce',
        cost: ['volt', 'volt'],
        damage: '60',
        text: 'Flip a coin. If heads, this attack does 20 more damage.',
      },
    ],
    weakness: 'terra',
    retreat: 1,
    flavor:
      'It races thunderheads across the plateau and always arrives a little before the thunder.',
    illustrator: 'Juniper Holt',
    art: { composition: 'window', speciesId: sp('voltail'), pose: 'action', seed: 3601 },
    baseValueCents: dollars(0.21),
    playability: 0.25,
  }),
  emd(37, {
    name: 'Thundervixen',
    kind: 'creature',
    rarity: 'rare',
    speciesId: sp('thundervixen'),
    element: 'volt',
    stage: 'stage2',
    hp: 150,
    attacks: [
      {
        name: 'Crackling Mane',
        cost: ['volt'],
        damage: '30',
        text: 'Your opponent’s Active creature is now Paralyzed.',
      },
      { name: 'Voltage Rush', cost: ['volt', 'volt', 'neutral'], damage: '120' },
    ],
    weakness: 'terra',
    retreat: 2,
    flavor: 'Where it runs, the grass stands on end for an hour afterwards.',
    illustrator: 'Yuki Morrow',
    art: { composition: 'window', speciesId: sp('thundervixen'), seed: 3701 },
    baseValueCents: dollars(0.58),
    playability: 0.4,
  }),
  emd(38, {
    name: 'Thundervixen Nova',
    kind: 'creature',
    rarity: 'ultraRare',
    speciesId: sp('thundervixen'),
    element: 'volt',
    stage: 'nova',
    hp: 240,
    ability: {
      name: 'Storm Bloom',
      text: 'Once during your turn, you may attach a Volt Essence from your deck to one of your Benched creatures.',
    },
    attacks: [
      {
        name: 'Nova Tempest',
        cost: ['volt', 'volt', 'volt'],
        damage: '220',
        text: 'Discard all Essence from this creature.',
      },
    ],
    weakness: 'terra',
    retreat: 2,
    flavor: 'A storm that learned to run.',
    illustrator: 'Yuki Morrow',
    art: {
      composition: 'window',
      speciesId: sp('thundervixen'),
      pose: 'action',
      timeOfDay: 'night',
      seed: 3801,
    },
    baseValueCents: dollars(6.67),
    playability: 0.65,
  }),
  // ---- Terra ----
  emd(39, {
    name: 'Pebblit',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('pebblit'),
    element: 'terra',
    stage: 'basic',
    hp: 70,
    attacks: [
      { name: 'Pebble Toss', cost: ['terra'], damage: '10' },
      { name: 'Rockslide Romp', cost: ['terra', 'neutral'], damage: '30' },
    ],
    weakness: 'bloom',
    retreat: 2,
    flavor: 'It collects shiny stones and keeps the best one under its tongue.',
    illustrator: 'Bo Strand',
    art: { composition: 'window', speciesId: sp('pebblit'), pose: 'happy', seed: 3901 },
    baseValueCents: dollars(0.07),
    playability: 0.05,
  }),
  // ---- Neutral ----
  emd(62, {
    name: 'Chirpip',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('chirpip'),
    element: 'neutral',
    stage: 'basic',
    hp: 40,
    attacks: [
      { name: 'Peep Peep', cost: ['neutral'], text: 'Draw a card.' },
      { name: 'Tiny Peck', cost: ['neutral', 'neutral'], damage: '20' },
    ],
    weakness: 'volt',
    resistance: 'terra',
    retreat: 1,
    flavor: 'It practices flying every morning. It has not left the ground yet. It is very proud.',
    illustrator: 'Talia Brightwater',
    art: { composition: 'window', speciesId: sp('chirpip'), pose: 'happy', seed: 6201 },
    baseValueCents: dollars(0.06),
    playability: 0.1,
  }),
  emd(64, {
    name: 'Galewing',
    kind: 'creature',
    rarity: 'uncommon',
    speciesId: sp('galewing'),
    element: 'neutral',
    stage: 'stage1',
    hp: 80,
    attacks: [
      {
        name: 'Tailwind',
        cost: ['neutral'],
        text: 'Switch your Active creature with one of your Benched creatures.',
      },
      { name: 'Wing Cut', cost: ['neutral', 'neutral'], damage: '40' },
    ],
    weakness: 'volt',
    resistance: 'terra',
    retreat: 0,
    flavor: 'It naps in mid-air on the trade winds and wakes up somewhere new.',
    illustrator: 'Talia Brightwater',
    art: { composition: 'window', speciesId: sp('galewing'), pose: 'action', seed: 6401 },
    baseValueCents: dollars(0.12),
    playability: 0.1,
  }),
  emd(65, {
    name: 'Stormcrest',
    kind: 'creature',
    rarity: 'rare',
    speciesId: sp('stormcrest'),
    element: 'neutral',
    stage: 'stage2',
    hp: 140,
    attacks: [
      { name: 'Gale Dive', cost: ['neutral', 'neutral'], damage: '60' },
      {
        name: 'Eye of the Storm',
        cost: ['neutral', 'neutral', 'neutral'],
        damage: '110',
        text: 'This attack’s damage isn’t affected by Resistance.',
      },
    ],
    weakness: 'volt',
    resistance: 'terra',
    retreat: 1,
    flavor: 'It flies straight into thunderstorms to see what is on the other side.',
    illustrator: 'Talia Brightwater',
    art: { composition: 'window', speciesId: sp('stormcrest'), timeOfDay: 'dusk', seed: 6501 },
    baseValueCents: dollars(0.38),
    playability: 0.3,
  }),
  emd(68, {
    name: 'Mimicat',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('mimicat'),
    element: 'neutral',
    stage: 'basic',
    hp: 60,
    attacks: [
      {
        name: 'Copycat',
        cost: ['neutral', 'neutral'],
        text: 'Choose 1 of your opponent’s Active creature’s attacks and use it as this attack.',
      },
    ],
    weakness: 'terra',
    retreat: 1,
    flavor: 'Ask three people what color Mimicat is and you will get four answers.',
    illustrator: 'Ezra Quill',
    art: { composition: 'window', speciesId: sp('mimicat'), seed: 6801 },
    baseValueCents: dollars(0.1),
    playability: 0.2,
  }),
  emd(70, {
    name: 'Snoozle',
    kind: 'creature',
    rarity: 'common',
    speciesId: sp('snoozle'),
    element: 'neutral',
    stage: 'basic',
    hp: 90,
    attacks: [
      { name: 'Big Yawn', cost: ['neutral'], text: 'Both Active creatures are now Asleep.' },
      { name: 'Pillow Flop', cost: ['neutral', 'neutral', 'neutral'], damage: '50' },
    ],
    weakness: 'terra',
    retreat: 3,
    flavor: 'It is awake for about four minutes a day and spends them looking for a comfier spot.',
    illustrator: 'Ezra Quill',
    art: { composition: 'window', speciesId: sp('snoozle'), timeOfDay: 'dusk', seed: 7001 },
    baseValueCents: dollars(0.11),
    playability: 0.15,
  }),
  // ---- Tactics: Items ----
  emd(73, {
    name: 'Glimmer Potion',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    rulesText: 'Heal 30 damage from 1 of your creatures.',
    flavor: 'Shake well. Do not drink the glow.',
    illustrator: 'Pia Marlowe',
    art: {
      composition: 'window',
      biome: 'lagoon',
      seed: 7301,
      prop: {
        kind: 'potion',
        fx: 'bubbles',
        glow: '#9FFFE8',
        shape: 'round',
        glass: '#DDF7FF',
        liquid: '#2FD6B8',
        stopper: '#B07A4E',
        label: '#FFF3D6',
      },
    },
    baseValueCents: dollars(0.1),
    playability: 0.45,
  }),
  emd(74, {
    name: 'Spark Charm',
    kind: 'tactic',
    rarity: 'common',
    tacticType: 'item',
    rulesText: 'Draw 2 cards. If your Active creature is a Volt creature, draw 3 cards instead.',
    flavor: 'Rub it twice for luck. A third time voids the warranty.',
    illustrator: 'Pia Marlowe',
    art: {
      composition: 'window',
      biome: 'storm-meadow',
      timeOfDay: 'dusk',
      seed: 7401,
      prop: {
        kind: 'charm',
        fx: 'sparks',
        glow: '#9FE6FF',
        shape: 'star',
        metal: '#FFC94A',
        gem: '#3FA9F5',
      },
    },
    baseValueCents: dollars(0.1),
    playability: 0.35,
  }),
  emd(80, {
    name: 'Ember Lantern',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'item',
    rulesText: 'Attach an Ember Essence from your discard pile to 1 of your Ember creatures.',
    flavor: 'Lit from the caldera itself. It has never gone out.',
    illustrator: 'Pia Marlowe',
    art: {
      composition: 'window',
      biome: 'volcano-dawn',
      timeOfDay: 'night',
      seed: 8001,
      prop: {
        kind: 'lantern',
        fx: 'embers',
        glow: '#FFB347',
        frame: '#4A3A3E',
        glass: '#FFD9A0',
        flame: '#FF9A3D',
      },
    },
    baseValueCents: dollars(0.22),
    playability: 0.3,
  }),
  // ---- Tactics: Allies ----
  emd(85, {
    name: 'Ranger Tala',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'ally',
    rulesText:
      'Search your deck for up to 2 Basic creatures, reveal them and put them into your hand. Then shuffle your deck.',
    flavor: '“Every trail on this island leads somewhere warm.”',
    illustrator: 'Noor Haddad',
    art: {
      composition: 'window',
      biome: 'volcano-dawn',
      pose: 'happy',
      seed: 8501,
      prop: {
        kind: 'folk',
        fx: 'none',
        glow: '#FFE2A6',
        age: 'adult',
        skin: '#B97A56',
        hair: '#2E1F1A',
        hairStyle: 'bun',
        top: '#4E8A5A',
        bottom: '#C9B48A',
        accent: '#FF8A3D',
        hat: 'ranger',
        glasses: false,
      },
    },
    baseValueCents: dollars(0.22),
    playability: 0.45,
  }),
  emd(88, {
    name: 'Theo’s Advice',
    kind: 'tactic',
    rarity: 'rare',
    tacticType: 'ally',
    rulesText: 'Shuffle your hand into your deck. Then draw 6 cards.',
    flavor: '“Never sell a holo to a kid who’s saving up. Trade them a story instead.”',
    illustrator: 'Noor Haddad',
    art: {
      composition: 'window',
      biome: 'lagoon',
      timeOfDay: 'dusk',
      seed: 8801,
      prop: {
        kind: 'folk',
        fx: 'none',
        glow: '#FFE9B8',
        age: 'elder',
        skin: '#F0C9A8',
        hair: '#F2F0EA',
        hairStyle: 'tufts',
        top: '#8C3B4E',
        bottom: '#5A5F7A',
        accent: '#FFC93C',
        hat: 'none',
        glasses: true,
      },
    },
    baseValueCents: dollars(0.82),
    playability: 0.75,
  }),
  // ---- Tactics: Arenas ----
  emd(94, {
    name: 'Emberdawn Caldera',
    kind: 'tactic',
    rarity: 'uncommon',
    tacticType: 'arena',
    rulesText:
      'Once during each player’s turn, they may heal 10 damage from their Active Ember creature.',
    flavor: 'The island’s heart. Locals set their clocks by its glow.',
    illustrator: 'Lena Vossberg',
    art: { composition: 'window', biome: 'volcano-dawn', timeOfDay: 'dusk', seed: 9401 },
    baseValueCents: dollars(0.22),
    playability: 0.35,
  }),
  emd(97, {
    name: 'Thunderhead Plateau',
    kind: 'tactic',
    rarity: 'rare',
    tacticType: 'arena',
    rulesText:
      'Volt creatures in play (both yours and your opponent’s) pay 1 less Essence to retreat.',
    flavor: 'Up here, every hair you own has an opinion about the weather.',
    illustrator: 'Lena Vossberg',
    art: { composition: 'window', biome: 'storm-meadow', timeOfDay: 'night', seed: 9701 },
    baseValueCents: dollars(0.49),
    playability: 0.45,
  }),
  // ---- Illustration Rares: one day on the island, dawn to night (Appendix A) ----
  emd(102, {
    name: 'Magmadillo',
    kind: 'creature',
    rarity: 'illustrationRare',
    speciesId: sp('magmadillo'),
    element: 'ember',
    stage: 'basic',
    hp: 80,
    attacks: [
      {
        name: 'Sunrise Bask',
        cost: ['ember', 'neutral'],
        damage: '40',
        text: 'Heal 20 damage from this creature.',
      },
    ],
    weakness: 'tide',
    retreat: 2,
    flavor: 'Dawn: the first warm rock of the day is always taken.',
    illustrator: 'Sora Lind',
    art: { composition: 'fullArt', speciesId: sp('magmadillo'), pose: 'happy', seed: 10201 },
    baseValueCents: dollars(8),
    playability: 0.15,
  }),
  emd(105, {
    name: 'Boltbuck',
    kind: 'creature',
    rarity: 'illustrationRare',
    speciesId: sp('boltbuck'),
    element: 'volt',
    stage: 'basic',
    hp: 90,
    attacks: [{ name: 'Noon Thunder', cost: ['volt', 'volt'], damage: '70' }],
    weakness: 'terra',
    retreat: 2,
    flavor: 'Noon: the herd runs with the storm across the high plateau.',
    illustrator: 'Sora Lind',
    art: { composition: 'fullArt', speciesId: sp('boltbuck'), pose: 'action', seed: 10501 },
    baseValueCents: dollars(9.78),
    playability: 0.2,
  }),
  emd(108, {
    name: 'Sploot',
    kind: 'creature',
    rarity: 'illustrationRare',
    speciesId: sp('sploot'),
    element: 'tide',
    stage: 'basic',
    hp: 70,
    attacks: [
      {
        name: 'Lagoon Lullaby',
        cost: ['tide', 'neutral'],
        damage: '50',
        text: 'Both creatures fall Asleep.',
      },
    ],
    weakness: 'volt',
    retreat: 2,
    flavor: 'At dusk, whole families of Sploot drift together, humming to the tide.',
    illustrator: 'Sora Lind',
    art: {
      composition: 'fullArt',
      speciesId: sp('sploot'),
      pose: 'happy',
      timeOfDay: 'dusk',
      seed: 10801,
    },
    baseValueCents: dollars(15.64),
    playability: 0.15,
  }),
  emd(114, {
    name: 'Sparkit',
    kind: 'creature',
    rarity: 'illustrationRare',
    speciesId: sp('sparkit'),
    element: 'volt',
    stage: 'basic',
    hp: 70,
    attacks: [
      { name: 'Starlight Tail', cost: ['volt', 'neutral'], damage: '50', text: 'Draw a card.' },
    ],
    weakness: 'terra',
    retreat: 1,
    flavor: 'Night: on the plateau, one of the stars is wagging.',
    illustrator: 'Sora Lind',
    art: {
      composition: 'fullArt',
      speciesId: sp('sparkit'),
      pose: 'happy',
      timeOfDay: 'night',
      seed: 11401,
    },
    baseValueCents: dollars(22.81),
    playability: 0.15,
  }),
  // ---- Secret Rares ----
  emd(117, {
    name: 'Infernox',
    kind: 'creature',
    rarity: 'secretRare',
    speciesId: sp('infernox'),
    element: 'ember',
    stage: 'stage2',
    hp: 170,
    attacks: [{ name: 'Golden Inferno', cost: ['ember', 'ember', 'ember'], damage: '180' }],
    weakness: 'tide',
    retreat: 3,
    flavor: 'Gilded by the caldera’s light, it guards the island’s oldest secret.',
    illustrator: 'Kaito Brenner',
    art: {
      composition: 'fullArt',
      speciesId: sp('infernox'),
      pose: 'action',
      timeOfDay: 'dusk',
      seed: 11701,
    },
    baseValueCents: dollars(44.43),
    playability: 0.35,
  }),
  emd(121, {
    name: 'Emberpup',
    kind: 'creature',
    rarity: 'secretRare',
    speciesId: sp('emberpup'),
    element: 'ember',
    stage: 'basic',
    hp: 60,
    attacks: [{ name: 'Golden Blaze', cost: ['ember', 'ember'], damage: '70' }],
    weakness: 'tide',
    retreat: 1,
    flavor: 'Legends say a golden Emberpup lights the first sunrise of every season.',
    illustrator: 'Kaito Brenner',
    art: { composition: 'fullArt', speciesId: sp('emberpup'), pose: 'action', seed: 12101 },
    baseValueCents: dollars(27.57),
    playability: 0.1,
  }),
  // ---- Mythic Rare ----
  emd(130, {
    name: 'Solaryx',
    kind: 'creature',
    rarity: 'mythicRare',
    speciesId: sp('solaryx'),
    element: 'ember',
    stage: 'legend',
    hp: 220,
    ability: {
      name: 'Gold Crown',
      text: 'Your Ember creatures’ attacks do 30 more damage to your opponent’s Active creature.',
    },
    attacks: [
      { name: 'Sunrise Eternal', cost: ['ember', 'ember', 'ember', 'neutral'], damage: '230' },
    ],
    weakness: 'tide',
    retreat: 2,
    flavor: 'Once in an age, the sun phoenix wears its crown. Then dawn lasts all day.',
    illustrator: 'Juniper Holt',
    art: {
      composition: 'fullArt',
      speciesId: sp('solaryx'),
      pose: 'happy',
      timeOfDay: 'day',
      seed: 13001,
    },
    baseValueCents: dollars(200),
    playability: 0.5,
  }),
];

/** Standard modern Glimmerkin booster (docs/02 §11.1). */
export const gkModernBooster: PackConfigDef = {
  id: 'gk.pack.modern',
  cardsPerPack: 10,
  slots: [
    { count: 5, table: [{ rarity: 'common', weight: 1 }] },
    { count: 3, table: [{ rarity: 'uncommon', weight: 1 }] },
    {
      count: 1,
      table: [
        { rarity: 'common', finish: 'reverseHolo', weight: 60 },
        { rarity: 'uncommon', finish: 'reverseHolo', weight: 30 },
        { rarity: 'rare', finish: 'reverseHolo', weight: 10 },
      ],
    },
    {
      count: 1,
      table: [
        { rarity: 'rare', weight: 62.5 },
        { rarity: 'holoRare', weight: 25 },
        { rarity: 'ultraRare', weight: 8 },
        { rarity: 'illustrationRare', weight: 3 },
        { rarity: 'secretRare', weight: 1.2 },
        { rarity: 'mythicRare', weight: 0.3 },
      ],
    },
  ],
  godPack: {
    chance: 1 / 2000,
    table: [
      { rarity: 'illustrationRare', weight: 75 },
      { rarity: 'secretRare', weight: 20 },
      { rarity: 'mythicRare', weight: 5 },
    ],
  },
  misprintChancePerCard: 1 / 5000,
};

/**
 * Starter deck lists: 59 fixed cards (one entry per copy) plus 1 guaranteed holo from a pool of 3
 * = 60 (docs/02 §10.1, §11.2). 18 creatures, 15 tactics, 26 basic Essences each.
 */
const EMBER_BLAZE: readonly (readonly [string, number])[] = [
  ['gk.emberdawn.012', 4], // Emberpup
  ['gk.emberdawn.014', 3], // Blazehound
  ['gk.emberdawn.015', 2], // Infernox
  ['gk.emberdawn.009', 3], // Magmadillo
  ['gk.emberdawn.062', 2], // Chirpip
  ['gk.emberdawn.070', 2], // Snoozle
  ['gk.emberdawn.068', 2], // Mimicat
  ['gk.emberdawn.073', 4], // Glimmer Potion
  ['gk.emberdawn.080', 3], // Ember Lantern
  ['gk.emberdawn.074', 2], // Spark Charm
  ['gk.emberdawn.085', 2], // Ranger Tala
  ['gk.emberdawn.088', 2], // Theo's Advice
  ['gk.emberdawn.094', 2], // Emberdawn Caldera
  ['gk.essence.001', 26], // Ember Essence
];

const VOLT_SURGE: readonly (readonly [string, number])[] = [
  ['gk.emberdawn.034', 4], // Sparkit
  ['gk.emberdawn.036', 3], // Voltail
  ['gk.emberdawn.037', 2], // Thundervixen
  ['gk.emberdawn.030', 2], // Boltbuck
  ['gk.emberdawn.031', 1], // Boltbuck (Static Stomp)
  ['gk.emberdawn.028', 2], // Zapcoon
  ['gk.emberdawn.062', 2], // Chirpip
  ['gk.emberdawn.064', 2], // Galewing
  ['gk.emberdawn.074', 4], // Spark Charm
  ['gk.emberdawn.073', 4], // Glimmer Potion
  ['gk.emberdawn.085', 2], // Ranger Tala
  ['gk.emberdawn.088', 2], // Theo's Advice
  ['gk.emberdawn.097', 3], // Thunderhead Plateau
  ['gk.essence.004', 26], // Volt Essence
];

function deckList(list: readonly (readonly [string, number])[]): { cardId: string }[] {
  return list.flatMap(([cardId, copies]) => Array.from({ length: copies }, () => ({ cardId })));
}

/** Emberdawn sealed products (docs/02 §10.1). */
export const emberdawnProducts: readonly ProductDef[] = [
  {
    id: 'gk.emberdawn.booster',
    kind: 'booster',
    name: 'Emberdawn Booster Pack',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(4.49),
    storageUnits: 1,
    perShelfSlot: 12,
    packConfigId: 'gk.pack.modern',
    contents: [],
  },
  {
    id: 'gk.emberdawn.blister',
    kind: 'blister',
    name: 'Emberdawn 3-Pack Blister',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(14.99),
    storageUnits: 2,
    perShelfSlot: 4,
    contents: [
      { type: 'pack', productId: 'gk.emberdawn.booster', count: 3 },
      // One black-star promo per blister (docs/02 §10.1, docs/03 §3.5).
      { type: 'promoPool', cardIds: ['gk.promo.001', 'gk.promo.002'], count: 1 },
    ],
  },
  {
    id: 'gk.emberdawn.starter-ember',
    kind: 'starterDeck',
    name: 'Emberdawn Starter Deck: Ember Blaze',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(14.99),
    storageUnits: 2,
    perShelfSlot: 4,
    contents: [
      { type: 'fixedCards', cards: deckList(EMBER_BLAZE) },
      {
        type: 'guaranteedHoloPool',
        cardIds: ['gk.emberdawn.010', 'gk.emberdawn.013', 'gk.emberdawn.017'],
      },
    ],
  },
  {
    id: 'gk.emberdawn.starter-volt',
    kind: 'starterDeck',
    name: 'Emberdawn Starter Deck: Volt Surge',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(14.99),
    storageUnits: 2,
    perShelfSlot: 4,
    contents: [
      { type: 'fixedCards', cards: deckList(VOLT_SURGE) },
      {
        type: 'guaranteedHoloPool',
        cardIds: ['gk.emberdawn.029', 'gk.emberdawn.032', 'gk.emberdawn.035'],
      },
    ],
  },
  {
    id: 'gk.emberdawn.box',
    kind: 'box',
    name: 'Emberdawn Booster Box (36 packs)',
    brandId: 'gk',
    setId: 'gk.emberdawn',
    msrpCents: dollars(161.64),
    storageUnits: 18,
    perShelfSlot: 1,
    contents: [{ type: 'pack', productId: 'gk.emberdawn.booster', count: 36 }],
  },
];
